/*
 * gpio_pins.c
 *
 *  Created on: 9 Mar 2023
 *      Author: dev
 */
#include "gpio_pins.h"
#include <stddef.h>

#define BUTTON_LOCAL_UP_PIN_PIN      (1)
#define BUTTON_LOCAL_UP_PIN_PORT     (0)

#define BUTTON_LOCAL_DOWN_PIN_PIN      (1)
#define BUTTON_LOCAL_DOWN_PIN_PORT     (0)

#define BUTTON_REMOTE_UP_PIN_PIN      (1)
#define BUTTON_REMOTE_UP_PIN_PORT     (0)

#define BUTTON_REMOTE_DOWN_PIN_PIN      (1)
#define BUTTON_REMOTE_DOWN_PIN_PORT     (0)

#define MOTOR_UP_PIN_PIN      (1)
#define MOTOR_UP_PIN_PORT     (0)

#define MOTOR_DOWN_PIN_PIN      (1)
#define MOTOR_DOWN_PIN_PORT     (0)

#define BUZZER_PIN_PIN      (1)
#define BUZZER_PIN_PORT     (0)

const struct gpio_pin gpio_pins[] = {
    { BUTTON_LOCAL_UP_PIN_ID, BUTTON_LOCAL_UP_PIN_PIN, BUTTON_LOCAL_UP_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { BUTTON_LOCAL_DOWN_PIN_ID, BUTTON_LOCAL_DOWN_PIN_PIN, BUTTON_LOCAL_DOWN_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { BUTTON_REMOTE_UP_PIN_ID, BUTTON_REMOTE_UP_PIN_PIN, BUTTON_REMOTE_UP_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { BUTTON_REMOTE_DOWN_PIN_ID, BUTTON_REMOTE_DOWN_PIN_PIN, BUTTON_REMOTE_DOWN_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { MOTOR_UP_PIN_ID, MOTOR_UP_PIN_PIN, MOTOR_UP_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { MOTOR_DOWN_PIN_ID, MOTOR_DOWN_PIN_PIN, MOTOR_DOWN_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { BUZZER_PIN_ID, BUZZER_PIN_PIN, BUZZER_PIN_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
};

static const uint8_t gpio_pins_size = sizeof(gpio_pins) / sizeof(gpio_pins[0]);

const struct gpio_pin * find_gpio_pin_context(enum board_input_pin_id pin_id)
{
    for (uint8_t id = 0; id < gpio_pins_size; id++)
    {
        if (gpio_pins[id].pin_id == pin_id)
        {
            return &gpio_pins[id];
        }
    }
    return NULL;
}
