/*
 * gpio_pins.c
 *
 *  Created on: 9 Mar 2023
 *      Author: dev
 */
#include <stddef.h>

#include "gpio_pins.h"
#include "stm32c0xx_ll_gpio.h"


/* User button */
#define BUTTON_LOCAL_UP_PIN_PIN   LL_GPIO_PIN_8
#define BUTTON_LOCAL_UP_PIN_PORT ((uint32_t)GPIOA)

#define BUTTON_LOCAL_DOWN_PIN_PIN      (LL_GPIO_PIN_4)
#define BUTTON_LOCAL_DOWN_PIN_PORT     ((uint32_t)GPIOA)

#define BUTTON_REMOTE_UP_PIN_PIN      (LL_GPIO_PIN_12)
#define BUTTON_REMOTE_UP_PIN_PORT     ((uint32_t)GPIOA)

#define BUTTON_REMOTE_DOWN_PIN_PIN      (LL_GPIO_PIN_11)
#define BUTTON_REMOTE_DOWN_PIN_PORT     ((uint32_t)GPIOA)

#define MOTOR_UP_PIN_PIN      (LL_GPIO_PIN_7)
#define MOTOR_UP_PIN_PORT     ((uint32_t)GPIOB)

#define MOTOR_DOWN_PIN_PIN      (LL_GPIO_PIN_14)
#define MOTOR_DOWN_PIN_PORT     ((uint32_t)GPIOC)

/* LED port */
#define BUZZER_PIN_PIN      (LL_GPIO_PIN_15)
#define BUZZER_PIN_PORT     ((uint32_t)GPIOC)

const struct gpio_pin gpio_pins[] = {
    { BUTTON_LOCAL_UP_PIN_ID, BUTTON_LOCAL_UP_PIN_PIN, BUTTON_LOCAL_UP_PIN_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_INPUT, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { BUTTON_LOCAL_DOWN_PIN_ID, BUTTON_LOCAL_DOWN_PIN_PIN, BUTTON_LOCAL_DOWN_PIN_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_INPUT, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { BUTTON_REMOTE_UP_PIN_ID, BUTTON_REMOTE_UP_PIN_PIN, BUTTON_REMOTE_UP_PIN_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_INPUT, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { BUTTON_REMOTE_DOWN_PIN_ID, BUTTON_REMOTE_DOWN_PIN_PIN, BUTTON_REMOTE_DOWN_PIN_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_INPUT, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { MOTOR_UP_PIN_ID, MOTOR_UP_PIN_PIN, MOTOR_UP_PIN_PORT, ACTIVE_HIGH, PIN_PULLDOWN, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW,0, BOTH_EDGES_INTERRUPTS },
    { MOTOR_DOWN_PIN_ID, MOTOR_DOWN_PIN_PIN, MOTOR_DOWN_PIN_PORT, ACTIVE_HIGH, PIN_PULLDOWN, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW,0, BOTH_EDGES_INTERRUPTS },
    { BUZZER_PIN_ID, BUZZER_PIN_PIN, BUZZER_PIN_PORT, ACTIVE_HIGH, PIN_NO_PULL, PIN_MODE_ALTERNATE, PIN_SPEED_LOW, LL_GPIO_AF_3, BOTH_EDGES_INTERRUPTS },
};

const uint8_t gpio_pins_size = sizeof(gpio_pins) / sizeof(gpio_pins[0]);


