package SwBuildingBlock
{


    part def MotorControl
    {
        doc /* Controls the motor based on events. */
    }

    part def Button
    {
        doc /* Handles implementation of buttons support.*/
    }

    part def UI
    {
        doc /* Controls the buzzer based on events. */
    }

    part def Controller
    {
        doc /* Based on Button events, controls roller shutter motor. */
    }

    part def Application
    {

    }

    part def Drivers 
    {

    }

    part def HAL
    {

    }
}