/*
 * gpio_pins.c
 *
 *  Created on: 9 Mar 2023
 *      Author: dev
 */
#include <stddef.h>

#include "gpio_pins.h"
#include "stm32f0xx_ll_gpio.h"

#define BUTTON_PIN       LL_GPIO_PIN_13
#define BUTTON_PORT ((uint32_t)GPIOC)
#define LED_PIN      LL_GPIO_PIN_5
#define LED_PORT     ((uint32_t)GPIOA)

#define VALVE_1_PIN   LL_GPIO_PIN_0
#define VALVE_1_PORT   ((uint32_t)GPIOA)
#define VALVE_2_PIN   LL_GPIO_PIN_1
#define VALVE_2_PORT   ((uint32_t)GPIOA)
#define VALVE_3_PIN   LL_GPIO_PIN_4
#define VALVE_3_PORT   ((uint32_t)GPIOA)
#define VALVE_4_PIN   LL_GPIO_PIN_0
#define VALVE_4_PORT   ((uint32_t)GPIOB)

#define ENCODER_CHANNEL_A_PIN   LL_GPIO_PIN_8
#define ENCODER_CHANNEL_A_PORT   ((uint32_t)GPIOA)
#define ENCODER_CHANNEL_B_PIN   LL_GPIO_PIN_9
#define ENCODER_CHANNEL_B_PORT   ((uint32_t)GPIOA)
#define ENCODER_SWITCH_PIN   LL_GPIO_PIN_10
#define ENCODER_SWITCH_PORT   ((uint32_t)GPIOA)

#define DISPLAY_D7_PIN   LL_GPIO_PIN_2
#define DISPLAY_D7_PORT   ((uint32_t)GPIOB)
#define DISPLAY_D6_PIN   LL_GPIO_PIN_10
#define DISPLAY_D6_PORT   ((uint32_t)GPIOB)
#define DISPLAY_D5_PIN   LL_GPIO_PIN_11
#define DISPLAY_D5_PORT   ((uint32_t)GPIOB)
#define DISPLAY_D4_PIN   LL_GPIO_PIN_12
#define DISPLAY_D4_PORT   ((uint32_t)GPIOB)
#define DISPLAY_RS_PIN   LL_GPIO_PIN_13
#define DISPLAY_RS_PORT   ((uint32_t)GPIOB)
#define DISPLAY_RW_PIN   LL_GPIO_PIN_14
#define DISPLAY_RW_PORT   ((uint32_t)GPIOB)
#define DISPLAY_E_PIN   LL_GPIO_PIN_15
#define DISPLAY_E_PORT   ((uint32_t)GPIOB)

const struct gpio_pin gpio_pins[] = {
    { LED_PIN_ID, LED_PIN, LED_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },
    { BUTTON_PIN_ID, BUTTON_PIN, BUTTON_PORT, ACTIVE_LOW, PIN_NO_PULL, PIN_MODE_INPUT, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },

    { VALVE_1_PIN_ID, VALVE_1_PIN, VALVE_1_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { VALVE_2_PIN_ID, VALVE_2_PIN, VALVE_2_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { VALVE_3_PIN_ID, VALVE_3_PIN, VALVE_3_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },
    { VALVE_4_PIN_ID, VALVE_4_PIN, VALVE_4_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_LOW, 0, BOTH_EDGES_INTERRUPTS },

    { ENCODER_CHANNEL_A, ENCODER_CHANNEL_A_PIN, ENCODER_CHANNEL_A_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_ALTERNATE, PIN_SPEED_HIGH, LL_GPIO_AF_2, BOTH_EDGES_INTERRUPTS },
    { ENCODER_CHANNEL_B, ENCODER_CHANNEL_B_PIN, ENCODER_CHANNEL_B_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_ALTERNATE, PIN_SPEED_HIGH, LL_GPIO_AF_2, BOTH_EDGES_INTERRUPTS },
    { ENCODER_SWITCH, ENCODER_SWITCH_PIN, ENCODER_SWITCH_PORT, ACTIVE_LOW, PIN_PULLUP, PIN_MODE_INPUT, PIN_SPEED_LOW, BOTH_EDGES_INTERRUPTS },

    { DISPLAY_D7, DISPLAY_D7_PIN, DISPLAY_D7_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_D6, DISPLAY_D6_PIN, DISPLAY_D6_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_D5, DISPLAY_D5_PIN, DISPLAY_D5_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_D4, DISPLAY_D4_PIN, DISPLAY_D4_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_RS, DISPLAY_RS_PIN, DISPLAY_RS_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_RW, DISPLAY_RW_PIN, DISPLAY_RW_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
    { DISPLAY_E, DISPLAY_E_PIN, DISPLAY_E_PORT, ACTIVE_HIGH, PIN_PULLUP, PIN_MODE_OUTPUT_PUSH_PULL, PIN_SPEED_HIGH, BOTH_EDGES_INTERRUPTS },
};

static const uint8_t gpio_pins_size = sizeof(gpio_pins)/sizeof(gpio_pins[0]);

